### ISSUE TITLE
Authentication token

### ISSUE THREAD

**Issue by little-kawa** [wectf/2020p#1]
- One extra quote at the end of line 57 in docker-compose.yaml

- When I try to run containers with `docker-compose up`, I got this error :
**ERROR: Head https://docker.pkg.github.com/v2/wectf/2020p/babyrev/manifests/latest: no basic auth credentials**

Then I tried to directly authenticate on "https://docker.pkg.github.com/v2/wectf/2020p/babyrev/manifests/latest:" and got this one :
**{"errors":[{"code":"UNAUTHORIZED","message":"Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured."}]}**

**Comment by shouc** [comment]
They are fixed now, thx for pointing out,
