### ISSUE TITLE
docker-compose up error on challenge hashtable

### ISSUE THREAD

**Issue by FantasqueX** [wectf/2020p#2]
I want to run challenges locally, and I got an error when executing "Run go build" challenge hashtable. I'm not familiar with go, and I don't how to solve that problem.

Here is the log.
![image](https://user-images.githubusercontent.com/46747123/124462076-e37e5280-ddc3-11eb-813a-a7ae1d763c2e.png)

```
------
 > [6/6] RUN go build:
#10 0.528 # vendor/github.com/gin-gonic/gin/internal/json
#10 0.528 ../vendor/github.com/gin-gonic/gin/internal/json/json.go:5:3: //go:build is not allowed in the standard library
------
executor failed running [/bin/sh -c go build]: exit code: 2
ERROR: Service 'hashtable' failed to build : Build failed
```

Looking forward to a solution, thanks a lot!

**Comment by shouc** [comment]
It is fixed now. Please try again.

**Comment by FantasqueX** [comment]
> It is fixed now. Please try again.

Thanks, but I found the same problem with challeng notebin, so I created a PR #3

**Comment by shouc** [comment]
thx
